# Generated by Django 4.2.11 on 2026-01-06 22:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], max_length=10)),
                ('capacity', models.FloatField(help_text='Available hours per week', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_subcontracted_material', models.BooleanField(default=False, help_text='Whether this is subcontracted material (BUILD dept only)')),
                ('subcontract_company', models.CharField(blank=True, choices=[('AMI', 'AMI'), ('VICER', 'VICER'), ('ITAX', 'ITAX'), ('MCI', 'MCI'), ('MG Electrical', 'MG Electrical')], help_text='Company name if subcontracted', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('facility', models.CharField(choices=[('AL', 'Facility A'), ('MI', 'Facility B'), ('MX', 'Facility C')], max_length=10)),
                ('number_of_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='capacity.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('SWITCH_LAYOUT_REVISION', 'Switch Layout Revision'), ('CONTROLS_DESIGN', 'Controls Design'), ('CONCEPT', 'Concept'), ('DETAIL_DESIGN', 'Detail Design'), ('CABINETS_FRAMES', 'Cabinets/Frames'), ('OVERALL_ASSEMBLY', 'Overall Assembly'), ('FINE_TUNING', 'Fine Tuning'), ('COMMISSIONING', 'Commissioning'), ('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('DEBUG', 'Debug'), ('RELEASE', 'Release'), ('RED_LINES', 'Red Lines'), ('SUPPORT', 'Support'), ('SUPPORT_MANUALS_FLOW_CHARTS', 'Support/Manuals/Flow Charts'), ('ROBOT_SIMULATION', 'Robot Simulation'), ('STANDARDS_REV_PROGRAMING_CONCEPT', 'Standards Rev/Programming Concept')], max_length=50, null=True)),
                ('week_start', models.IntegerField(help_text='1-based week number', validators=[django.core.validators.MinValueValidator(1)])),
                ('week_end', models.IntegerField(help_text='1-based week number', validators=[django.core.validators.MinValueValidator(1)])),
                ('department_start_date', models.DateField(blank=True, help_text='Actual start date for this specific department', null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stages', to='capacity.project')),
            ],
            options={
                'ordering': ['project', 'department', 'week_start'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('hours', models.FloatField(help_text='Total hours allocated', validators=[django.core.validators.MinValueValidator(0)])),
                ('scio_hours', models.FloatField(blank=True, help_text='Internal SCIO hours (BUILD/PRG only)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('external_hours', models.FloatField(blank=True, help_text='External/subcontracted hours (BUILD/PRG only)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stage', models.CharField(blank=True, choices=[('SWITCH_LAYOUT_REVISION', 'Switch Layout Revision'), ('CONTROLS_DESIGN', 'Controls Design'), ('CONCEPT', 'Concept'), ('DETAIL_DESIGN', 'Detail Design'), ('CABINETS_FRAMES', 'Cabinets/Frames'), ('OVERALL_ASSEMBLY', 'Overall Assembly'), ('FINE_TUNING', 'Fine Tuning'), ('COMMISSIONING', 'Commissioning'), ('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('DEBUG', 'Debug'), ('RELEASE', 'Release'), ('RED_LINES', 'Red Lines'), ('SUPPORT', 'Support'), ('SUPPORT_MANUALS_FLOW_CHARTS', 'Support/Manuals/Flow Charts'), ('ROBOT_SIMULATION', 'Robot Simulation'), ('STANDARDS_REV_PROGRAMING_CONCEPT', 'Standards Rev/Programming Concept')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional comment for this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='capacity.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='capacity.project')),
            ],
            options={
                'ordering': ['week_start_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action performed', max_length=255)),
                ('model_name', models.CharField(help_text='Model affected', max_length=50)),
                ('object_id', models.CharField(help_text='UUID of affected object', max_length=36)),
                ('changes', models.JSONField(blank=True, help_text='JSON of changes made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], max_length=10)),
                ('hours_allocated', models.FloatField(help_text='Budget hours per department (presupuesto/cotizado)', validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_utilized', models.FloatField(default=0, help_text='Hours utilized/used per department', validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_forecast', models.FloatField(default=0, help_text='Forecasted hours per department', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='capacity.project')),
            ],
            options={
                'ordering': ['project', 'department'],
                'unique_together': {('project', 'department')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='capacity_pr_start_d_e36c57_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='capacity_em_departm_76a201_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='capacity_em_is_acti_ead054_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentstageconfig',
            unique_together={('project', 'department')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['week_start_date'], name='capacity_as_week_st_46b7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee', 'week_start_date'], name='capacity_as_employe_ad3c72_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='capacity_ac_user_id_d0be55_idx'),
        ),
    ]
