# Generated by Django 4.2.11 on 2026-01-08 23:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0003_project_visible_in_departments_and_budget_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractedTeamCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(help_text='Company name (e.g., AMI, VICER, ITAX, etc.)', max_length=100)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('capacity', models.IntegerField(help_text='Number of personnel from this company', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'week_start_date'],
                'indexes': [models.Index(fields=['company', 'week_start_date'], name='capacity_su_company_dacfe0_idx')],
                'unique_together': {('company', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ScioTeamCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], max_length=10)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('capacity', models.FloatField(help_text='SCIO team capacity for this week', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', 'week_start_date'],
                'indexes': [models.Index(fields=['department', 'week_start_date'], name='capacity_sc_departm_8bb834_idx')],
                'unique_together': {('department', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='PrgExternalTeamCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(help_text='External team name', max_length=100)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('capacity', models.IntegerField(help_text='Number of personnel from this team', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team_name', 'week_start_date'],
                'indexes': [models.Index(fields=['team_name', 'week_start_date'], name='capacity_pr_team_na_95168f_idx')],
                'unique_together': {('team_name', 'week_start_date')},
            },
        ),
    ]
