# Generated by Django 4.2.11 on 2026-01-09 14:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0004_subcontractedteamcapacity_scioteamcapacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWeeklyTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], max_length=10)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('total_hours', models.FloatField(help_text='Total hours assigned for this department/week', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', 'week_start_date'],
                'indexes': [models.Index(fields=['department', 'week_start_date'], name='capacity_de_departm_482057_idx')],
                'unique_together': {('department', 'week_start_date')},
            },
        ),
    ]
