# Generated by Django 4.2.11 on 2026-01-09 23:15

from django.db import migrations


def create_missing_project_budgets(apps, schema_editor):
    """Create ProjectBudget entries for projects that don't have them."""
    Project = apps.get_model('capacity', 'Project')
    ProjectBudget = apps.get_model('capacity', 'ProjectBudget')

    departments = ['PM', 'MED', 'HD', 'MFG', 'BUILD', 'PRG']

    for project in Project.objects.all():
        # Check if this project has any budgets
        if project.budgets.count() == 0:
            # Create default budgets (0 hours) for all departments
            for dept in departments:
                ProjectBudget.objects.get_or_create(
                    project=project,
                    department=dept,
                    defaults={
                        'hours_allocated': 0,
                        'hours_utilized': 0,
                        'hours_forecast': 0,
                    }
                )


def reverse_create_missing_project_budgets(apps, schema_editor):
    """Reverse: Delete ProjectBudgets that were created with 0 allocated hours."""
    ProjectBudget = apps.get_model('capacity', 'ProjectBudget')

    # Delete all ProjectBudgets with 0 allocated hours (the ones we created)
    ProjectBudget.objects.filter(hours_allocated=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0005_departmentweeklytotal'),
    ]

    operations = [
        migrations.RunPython(
            create_missing_project_budgets,
            reverse_create_missing_project_budgets
        )
    ]
