# Generated by Django 4.2.11 on 2026-01-12

from django.db import migrations


def fix_corrupted_department_names(apps, schema_editor):
    """
    Fix corrupted department names in ProjectBudget.

    The frontend was incorrectly transforming department names like PM -> _p_m
    due to the transformKeysToSnake function transforming nested object keys.

    This migration:
    1. Deletes records with corrupted department names (those starting with _)
    2. The correct records will be created when users save projects again
    """
    ProjectBudget = apps.get_model('capacity', 'ProjectBudget')

    # Corrupted department names pattern: start with underscore
    # Valid departments are: PM, MED, HD, MFG, BUILD, PRG
    corrupted_budgets = ProjectBudget.objects.filter(department__startswith='_')

    count = corrupted_budgets.count()
    if count > 0:
        print(f'Deleting {count} ProjectBudget records with corrupted department names')
        corrupted_budgets.delete()
    else:
        print('No corrupted ProjectBudget records found')


def reverse_fix_corrupted_department_names(apps, schema_editor):
    """
    No reverse operation needed - we can't recreate corrupted data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0006_create_missing_project_budgets'),
    ]

    operations = [
        migrations.RunPython(
            fix_corrupted_department_names,
            reverse_fix_corrupted_department_names
        )
    ]
