# Generated by Django 4.2.11 on 2026-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0008_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
