# Generated by Django 4.2.11 on 2026-01-14 22:36

from django.db import migrations


def add_initial_employees(apps, schema_editor):
    """Add initial BUILD department employees"""
    Employee = apps.get_model('capacity', 'Employee')

    employees_data = [
        {
            'name': 'Bryan Hernández',
            'role': 'Ing. de ensamble electromecánico Jr',
            'department': 'BUILD',
            'capacity': 40,
        },
        {
            'name': 'Daniel Gámez',
            'role': 'Ing. de ensamble electromecánico',
            'department': 'BUILD',
            'capacity': 40,
        },
        {
            'name': 'Guadalupe Rivera',
            'role': 'Ing. de ensamble electromecánico Sr',
            'department': 'BUILD',
            'capacity': 40,
        },
        {
            'name': 'Victor Catalan',
            'role': 'Ing. de ensamble electromecánico',
            'department': 'BUILD',
            'capacity': 40,
        },
    ]

    for emp_data in employees_data:
        Employee.objects.get_or_create(
            name=emp_data['name'],
            department=emp_data['department'],
            defaults={
                'role': emp_data['role'],
                'capacity': emp_data['capacity'],
                'is_active': True,
                'is_subcontracted_material': False,
            }
        )


def remove_initial_employees(apps, schema_editor):
    """Remove initial employees (reverse migration)"""
    Employee = apps.get_model('capacity', 'Employee')
    Employee.objects.filter(
        name__in=['Bryan Hernández', 'Daniel Gámez', 'Guadalupe Rivera', 'Victor Catalan']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0009_add_verification_code'),
    ]

    operations = [
        migrations.RunPython(add_initial_employees, remove_initial_employees),
    ]
