# Generated by Django 4.2.11 on 2026-01-14 23:01

from django.db import migrations
from django.contrib.auth.models import User


def create_initial_user(apps, schema_editor):
    """Create initial user for login"""
    User.objects.get_or_create(
        username='MARCO.SOTO',
        defaults={
            'email': 'MARCO.SOTO@NA.SCIO-AUTOMATION.COM',
            'is_active': True,
        }
    )
    # Set password (only if user was just created)
    user = User.objects.get(username='MARCO.SOTO')
    if not user.check_password('Perrita26!'):
        user.set_password('Perrita26!')
        user.save()


def remove_initial_user(apps, schema_editor):
    """Remove initial user (reverse migration)"""
    User.objects.filter(username='MARCO.SOTO').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0010_add_initial_employees'),
    ]

    operations = [
        migrations.RunPython(create_initial_user, remove_initial_user),
    ]
