# Generated by Django 4.2.11 on 2026-01-15

from django.db import migrations


def add_department_employees(apps, schema_editor):
    """Add initial employees for all departments"""
    Employee = apps.get_model('capacity', 'Employee')

    # Default employees for each department (if they don't exist)
    employees_data = [
        # PM Department
        {
            'name': 'PM Employee 1',
            'role': 'Project Manager',
            'department': 'PM',
            'capacity': 40,
        },
        # MED Department
        {
            'name': 'MED Employee 1',
            'role': 'Mechanical Engineer',
            'department': 'MED',
            'capacity': 40,
        },
        # HD Department
        {
            'name': 'HD Employee 1',
            'role': 'Hardware Designer',
            'department': 'HD',
            'capacity': 40,
        },
        # MFG Department
        {
            'name': 'MFG Employee 1',
            'role': 'Manufacturing Engineer',
            'department': 'MFG',
            'capacity': 40,
        },
        # PRG Department
        {
            'name': 'PRG Employee 1',
            'role': 'Programmer',
            'department': 'PRG',
            'capacity': 40,
        },
    ]

    for emp_data in employees_data:
        # Only create if no employees exist in that department
        if not Employee.objects.filter(department=emp_data['department']).exists():
            Employee.objects.create(
                name=emp_data['name'],
                role=emp_data['role'],
                department=emp_data['department'],
                capacity=emp_data['capacity'],
                is_active=True,
                is_subcontracted_material=False,
            )
            print(f"Created employee for department: {emp_data['department']}")


def remove_department_employees(apps, schema_editor):
    """Remove initial employees (reverse migration)"""
    Employee = apps.get_model('capacity', 'Employee')
    Employee.objects.filter(
        name__in=[
            'PM Employee 1',
            'MED Employee 1',
            'HD Employee 1',
            'MFG Employee 1',
            'PRG Employee 1',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0011_add_initial_user'),
    ]

    operations = [
        migrations.RunPython(add_department_employees, remove_department_employees),
    ]
