# Generated by Django 4.2.11 on 2026-01-15

from django.db import migrations


def ensure_placeholder_employees(apps, schema_editor):
    """Ensure placeholder employees exist for all departments"""
    Employee = apps.get_model('capacity', 'Employee')

    # Placeholder employees for each department
    employees_data = [
        {
            'name': 'PM Employee 1',
            'role': 'Project Manager',
            'department': 'PM',
            'capacity': 40,
        },
        {
            'name': 'MED Employee 1',
            'role': 'Mechanical Engineer',
            'department': 'MED',
            'capacity': 40,
        },
        {
            'name': 'HD Employee 1',
            'role': 'Hardware Designer',
            'department': 'HD',
            'capacity': 40,
        },
        {
            'name': 'MFG Employee 1',
            'role': 'Manufacturing Engineer',
            'department': 'MFG',
            'capacity': 40,
        },
        {
            'name': 'PRG Employee 1',
            'role': 'Programmer',
            'department': 'PRG',
            'capacity': 40,
        },
    ]

    for emp_data in employees_data:
        obj, created = Employee.objects.get_or_create(
            name=emp_data['name'],
            defaults={
                'role': emp_data['role'],
                'department': emp_data['department'],
                'capacity': emp_data['capacity'],
                'is_active': True,
                'is_subcontracted_material': False,
            }
        )
        if created:
            print(f"Created placeholder employee: {emp_data['name']}")
        else:
            # Ensure the employee is active
            if not obj.is_active:
                obj.is_active = True
                obj.save()
                print(f"Activated placeholder employee: {emp_data['name']}")
            else:
                print(f"Placeholder employee already exists: {emp_data['name']}")


def noop(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0012_add_all_department_employees'),
    ]

    operations = [
        migrations.RunPython(ensure_placeholder_employees, noop),
    ]
