# Generated by Django 4.2.11 on 2026-01-19 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacity', '0013_ensure_placeholder_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(help_text='JWT refresh token for this session', unique=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information (user agent, IP, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Session creation timestamp')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='capacity_us_user_id_67e722_idx'), models.Index(fields=['refresh_token'], name='capacity_us_refresh_929c1e_idx')],
            },
        ),
    ]
