# Generated by Django 4.2.11 on 2026-01-28 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0015_remove_test_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prgexternalteamcapacity',
            name='capacity',
            field=models.FloatField(help_text='Number of personnel from this team', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subcontractedteamcapacity',
            name='capacity',
            field=models.FloatField(help_text='Number of personnel from this company', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
