# Generated by Django 4.2.11 on 2026-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hidden_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when project was hidden via soft delete.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Hidden projects are excluded from active UI lists.'),
        ),
    ]
