# Generated by Django 4.2.11 on 2026-02-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0019_project_hidden_at_project_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='change_order',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional Change Order this assignment belongs to',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assignments',
                to='capacity.projectchangeorder',
            ),
        ),
    ]

