# Generated by Django 4.2.11 on 2026-02-19 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0020_assignment_change_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='scioteamcapacity',
            name='pto',
            field=models.FloatField(default=0, help_text='PTO adjustment to subtract from SCIO team capacity for this week', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='scioteamcapacity',
            name='training',
            field=models.FloatField(default=0, help_text='Training adjustment to subtract from SCIO team capacity for this week', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
