# Generated by Django 4.2.28 on 2026-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0022_project_is_high_probability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('employee', 'project', 'week_start_date')},
        ),
    ]
