# Generated by Django 4.2.28 on 2026-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0023_assignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when project was marked as closed.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks project as closed/completed. Closed projects are hidden from Capacity Matrix by default.'),
        ),
    ]
