# Generated by Django 4.2.28 on 2026-08-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0024_project_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department_override',
            field=models.CharField(blank=True, choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC')], help_text="Optional override for which department this assignment's hours count against, used when the employee is temporarily supporting a department other than their own (e.g. an HD engineer covering BUILD for a week). Leave empty to use the employee's home department (Employee.department) — the default, backward-compatible behavior.", max_length=10, null=True),
        ),
    ]
