# Generated by Django 4.2.28 on 2026-08-04 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0025_assignment_department_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The specific calendar day this entry is for')),
                ('entry_type', models.CharField(choices=[('PROJECT', 'Project Work'), ('OIL', 'Project Issue Resolution'), ('IND', 'Indirect Time'), ('VAC', 'Vacation')], max_length=10)),
                ('hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_time_entries', to='capacity.employee')),
                ('project', models.ForeignKey(blank=True, help_text='Required for PROJECT and OIL entries (which project the hours belong to). Must be empty for IND/VAC.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_time_entries', to='capacity.project')),
            ],
            options={
                'ordering': ['date', 'employee'],
                'indexes': [models.Index(fields=['date'], name='capacity_da_date_d69a5d_idx'), models.Index(fields=['employee', 'date'], name='capacity_da_employe_b99d2a_idx'), models.Index(fields=['project'], name='capacity_da_project_86f5a2_idx')],
                'unique_together': {('employee', 'date', 'entry_type', 'project')},
            },
        ),
    ]
