# Generated by Django 4.2.28 on 2026-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0026_dailytimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Fecha de alta: date the employee started working with us', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Fecha de baja: date the employee stopped working with us', null=True),
        ),
    ]
