# Generated by Django 4.2.28 on 2026-09-08 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacity', '0027_employee_hire_date_employee_termination_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('report_dates_processed', models.JSONField(blank=True, default=list, help_text='List of report dates (ISO) found in the uploaded file')),
                ('new_projects_created', models.JSONField(blank=True, default=list, help_text='Project numbers auto-created by this import')),
                ('weekly_actuals_written', models.IntegerField(default=0)),
                ('job_codes_seeded_only', models.JSONField(blank=True, default=list, help_text='Job codes seen for the first time this run (baseline only, no diff created)')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, db_index=True, help_text="Canonical project number/code (e.g. '3268' or '3268-CO01' for a change order treated as its own project). Used to reliably match external reports (e.g. Finance actuals) to this project.", max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='department_override',
            field=models.CharField(blank=True, choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], help_text="Optional override for which department this assignment's hours count against, used when the employee is temporarily supporting a department other than their own (e.g. an HD engineer covering BUILD for a week). Leave empty to use the employee's home department (Employee.department) — the default, backward-compatible behavior.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='departmentstageconfig',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentweeklytotal',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='projectchangeorder',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scioteamcapacity',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceJobCumulative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_code', models.CharField(help_text="Raw Job code as it appears in the Finance report, e.g. '3268-A'", max_length=30)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=15)),
                ('cumulative_hours', models.FloatField(default=0, help_text='Last known cumulative hours reported for this job/department')),
                ('last_report_date', models.DateField(help_text='Report date this cumulative value came from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_code', 'department'],
                'unique_together': {('job_code', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDepartmentWeeklyActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=15)),
                ('week_start_date', models.DateField(help_text='Start date of the week (ISO format YYYY-MM-DD)')),
                ('hours', models.FloatField(help_text='Hours worked this week, per the Finance report diff. Can be negative when Finance issues a correction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_actuals', to='capacity.project')),
                ('source_import', models.ForeignKey(blank=True, help_text='The import run that most recently wrote this row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuals', to='capacity.financeimportlog')),
            ],
            options={
                'ordering': ['project', 'department', 'week_start_date'],
                'indexes': [models.Index(fields=['department', 'week_start_date'], name='capacity_pr_departm_cbc5ec_idx'), models.Index(fields=['project', 'department'], name='capacity_pr_project_14bc84_idx')],
                'unique_together': {('project', 'department', 'week_start_date')},
            },
        ),
    ]
