# Generated by Django 4.2.28 on 2026-09-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacity', '0028_financeimportlog_project_project_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScioHeadcountEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PM', 'Project Manager'), ('MED', 'Mechanical Design'), ('HD', 'Hardware Design'), ('MFG', 'Manufacturing'), ('BUILD', 'Assembly'), ('PRG', 'Programming PLC'), ('PURCHASING', 'Purchasing')], max_length=10)),
                ('effective_date', models.DateField(help_text='Calendar date the headcount change takes effect')),
                ('delta', models.FloatField(help_text='Signed headcount change, e.g. +1 for a hire, -2 for two departures')),
                ('comment', models.TextField(blank=True, help_text='Optional context, e.g. who joined/left and why')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scio_headcount_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'effective_date'],
                'indexes': [models.Index(fields=['department', 'effective_date'], name='capacity_sc_departm_ddbe30_idx')],
            },
        ),
    ]
