# Generated by Django 4.2.28 on 2026-09-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0029_scioheadcountevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('employee', 'project', 'week_start_date', 'stage')},
        ),
    ]
